#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Jungle.Bootstrap
{
    /// <summary>
    /// Compares the plugin's files on disk against the list its .unitypackage shipped, and reports
    /// when they no longer match.
    ///
    /// Unity's import window skips unchecked folders instead of removing them, so updating with
    /// folders unchecked leaves the previous version's files sitting next to the new ones. What the
    /// customer sees is a compile error nowhere near the real cause, or a native library that no
    /// longer matches the code calling into it, with nothing pointing back at the import.
    ///
    /// Some folders are genuinely optional (the MCP bridges, say) and the manifest marks them, so
    /// leaving one out entirely passes quietly. Leaving out part of one does not.
    ///
    /// This lives in the bootstrap assembly, which references nothing, so it keeps compiling (and
    /// keeps reporting) when every other assembly in the plugin is broken.
    ///
    /// The manifest is generated by the Jungle Publisher at export. In the dev project the const
    /// below is empty and the whole check is inert.
    /// </summary>
    [InitializeOnLoad]
    internal static class JungleInstallCheck
    {
        // Stamped by JunglePublisher at export time. Empty in the dev project.
        private const string ManifestAsset = "Assets/Plugins/Jungle/Grabbit/Editor/Bootstrap/Grabbit.jungle-install.txt";

        /// <summary>How many offending files the console lists before summarising the rest.</summary>
        private const int MaxListed = 12;

        static JungleInstallCheck()
        {
            if (ManifestAsset.Length == 0)
                return;

            EditorApplication.delayCall += Run;
        }

        private static void Run()
        {
            string projectRoot;
            try { projectRoot = Directory.GetParent(Application.dataPath)!.FullName; }
            catch (Exception) { return; }

            var manifestFull = Path.Combine(projectRoot, ManifestAsset.Replace('/', Path.DirectorySeparatorChar));

            string[] lines;
            try
            {
                if (!File.Exists(manifestFull))
                    return; // the manifest itself was skipped on import; nothing to compare against

                lines = File.ReadAllLines(manifestFull);
            }
            catch (Exception)
            {
                return;
            }

            var plugin = "This Jungle plugin";
            var stamp = string.Empty;
            var missingCritical = new List<string>();
            var missingContent = new List<string>();
            var stale = new List<string>();
            var optional = new List<OptionalFolder>();

            foreach (var line in lines)
            {
                if (line.Length == 0 || line[0] == '#' || line == "---")
                    continue;

                if (line.StartsWith("plugin=", StringComparison.Ordinal))
                {
                    plugin = line.Substring("plugin=".Length);
                    continue;
                }

                if (line.StartsWith("stamp=", StringComparison.Ordinal))
                {
                    stamp = line.Substring("stamp=".Length);
                    continue;
                }

                if (line.StartsWith("optional=", StringComparison.Ordinal))
                {
                    optional.Add(new OptionalFolder(line.Substring("optional=".Length)));
                    continue;
                }

                var parts = line.Split('\t');
                if (parts.Length != 4)
                    continue;

                bool critical = parts[0] == "X";
                var assetPath = parts[3];
                var full = Path.Combine(projectRoot, assetPath.Replace('/', Path.DirectorySeparatorChar));

                var folder = OptionalFolderFor(optional, assetPath);
                folder?.Count();

                if (!File.Exists(full))
                {
                    if (folder != null)
                        folder.Missing(assetPath, critical);
                    else
                        (critical ? missingCritical : missingContent).Add(assetPath);
                    continue;
                }

                if (!critical)
                    continue;

                if (!long.TryParse(parts[1], out long expectedLength))
                    continue;

                long actualLength;
                try { actualLength = new FileInfo(full).Length; }
                catch (Exception) { continue; }

                if (actualLength != expectedLength)
                {
                    stale.Add(assetPath);
                    continue;
                }

                // Large files (the native libraries) ship without a hash and are length checked only.
                if (parts[2] == "-")
                    continue;

                var actualHash = HashFile(full);
                if (actualHash != null && !string.Equals(actualHash, parts[2], StringComparison.OrdinalIgnoreCase))
                    stale.Add(assetPath);
            }

            // A folder marked optional may be left out of the import wholesale, so an entirely absent
            // one is a choice, not a fault. Missing only part of it still is one: nobody picks half a
            // folder, and what is left behind references code that is not there.
            foreach (var folder in optional)
            {
                if (folder.AllMissing)
                    continue;

                missingCritical.AddRange(folder.MissingCritical);
                missingContent.AddRange(folder.MissingContent);
            }

            // Reported once per shipped version: a second pass on every domain reload would nag, and the
            // answer (re-import the package) does not change until the files do.
            var reportedKey = $"JungleInstallCheck_{plugin}_{stamp}_{Application.dataPath}";
            if (EditorPrefs.GetBool(reportedKey, false))
                return;

            if (missingCritical.Count == 0 && missingContent.Count == 0 && stale.Count == 0)
            {
                EditorPrefs.SetBool(reportedKey, true);
                return;
            }

            Report(plugin, missingCritical, missingContent, stale);
            EditorPrefs.SetBool(reportedKey, true);
        }

        /// <summary>
        /// A folder the package declares as safe to leave out of the import, and the tally of what
        /// arrived from it. Only a folder that is missing in full counts as deliberately skipped.
        /// </summary>
        private sealed class OptionalFolder
        {
            private readonly string prefix;
            private int total;

            internal readonly List<string> MissingCritical = new List<string>();
            internal readonly List<string> MissingContent = new List<string>();

            internal OptionalFolder(string assetFolder)
            {
                prefix = assetFolder.TrimEnd('/') + "/";
            }

            internal string Prefix => prefix;

            internal bool AllMissing => MissingCritical.Count + MissingContent.Count == total;

            internal void Count() => total++;

            internal void Missing(string assetPath, bool critical) =>
                (critical ? MissingCritical : MissingContent).Add(assetPath);
        }

        /// <summary>
        /// The innermost optional folder holding this file, or null when it sits outside all of them.
        /// </summary>
        private static OptionalFolder OptionalFolderFor(List<OptionalFolder> folders, string assetPath)
        {
            OptionalFolder best = null;
            foreach (var folder in folders)
            {
                if (!assetPath.StartsWith(folder.Prefix, StringComparison.OrdinalIgnoreCase))
                    continue;
                if (best == null || folder.Prefix.Length > best.Prefix.Length)
                    best = folder;
            }

            return best;
        }

        private static void Report(string plugin, List<string> missingCritical,
            List<string> missingContent, List<string> stale)
        {
            var counts = new List<string>();
            if (stale.Count > 0)
                counts.Add($"{stale.Count} left over from an older version");
            if (missingCritical.Count > 0)
                counts.Add($"{missingCritical.Count} missing (code or libraries)");
            if (missingContent.Count > 0)
                counts.Add($"{missingContent.Count} missing (assets)");

            var detail = new StringBuilder();
            detail.Append($"{plugin}: the files in your project do not match the version that was imported: ")
                  .Append(string.Join(", ", counts.ToArray())).Append(".\n\n")
                  .Append("Unity's import window skips folders you uncheck instead of removing them, so ")
                  .Append("importing an update with folders unchecked leaves old files in place next to ")
                  .Append("the new ones. Re-import the package with every folder checked to fix this.\n");

            AppendList(detail, "Left over from an older version", stale);
            AppendList(detail, "Missing code or libraries", missingCritical);
            AppendList(detail, "Missing assets", missingContent);

            bool severe = stale.Count > 0 || missingCritical.Count > 0;
            if (severe)
                Debug.LogError(detail.ToString());
            else
                Debug.LogWarning(detail.ToString());

            // Missing content on its own is often deliberate (someone deleting a demo folder they don't
            // want), so that case stays in the console. Stale or missing code is not something anyone
            // chooses, and it breaks the project, so it interrupts.
            if (!severe)
                return;

            EditorUtility.DisplayDialog(
                $"{plugin}: incomplete import",
                $"Some {plugin} files are missing or left over from an older version, which will cause " +
                "errors that look unrelated.\n\n" +
                "Unity skips folders you uncheck in the import window instead of removing them, so an " +
                "update imported that way mixes old and new files.\n\n" +
                "Re-import the package with every folder checked. The console lists the affected files.",
                "OK");
        }

        private static void AppendList(StringBuilder detail, string title, List<string> paths)
        {
            if (paths.Count == 0)
                return;

            detail.Append('\n').Append(title).Append(":\n");
            for (int i = 0; i < paths.Count && i < MaxListed; i++)
                detail.Append("  ").Append(paths[i]).Append('\n');
            if (paths.Count > MaxListed)
                detail.Append($"  ... and {paths.Count - MaxListed} more\n");
        }

        private static string HashFile(string fullPath)
        {
            try
            {
                using var stream = File.OpenRead(fullPath);
                using var sha = SHA1.Create();
                var bytes = sha.ComputeHash(stream);
                var hex = new StringBuilder(bytes.Length * 2);
                foreach (var b in bytes)
                    hex.Append(b.ToString("x2"));
                return hex.ToString();
            }
            catch (Exception)
            {
                return null;
            }
        }
    }
}
#endif
